name: torch117
channels:
  - defaults
  - nvidia
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cuda-cccl_win-64=13.0.85
  - cuda-command-line-tools=13.0.2
  - cuda-compiler=13.0.2
  - cuda-crt-dev_win-64=13.0.88
  - cuda-crt-tools=13.0.88
  - cuda-ctadvisor=13.0.85
  - cuda-cudart=13.0.96
  - cuda-cudart-dev=13.0.96
  - cuda-cudart-dev_win-64=13.0.96
  - cuda-cudart-static=13.0.96
  - cuda-cudart-static_win-64=13.0.96
  - cuda-cudart_win-64=13.0.96
  - cuda-cuobjdump=13.0.85
  - cuda-cupti=13.0.85
  - cuda-cupti-dev=13.0.85
  - cuda-cuxxfilt=13.0.85
  - cuda-documentation=12.4.127
  - cuda-libraries=13.0.2
  - cuda-libraries-dev=13.0.2
  - cuda-nvcc=13.0.88
  - cuda-nvcc-dev_win-64=13.0.88
  - cuda-nvcc-impl=13.0.88
  - cuda-nvcc-tools=13.0.88
  - cuda-nvcc_win-64=13.0.88
  - cuda-nvdisasm=13.0.85
  - cuda-nvml-dev=13.0.87
  - cuda-nvprune=13.0.85
  - cuda-nvrtc=13.0.88
  - cuda-nvrtc-dev=13.0.88
  - cuda-nvvm-dev_win-64=13.0.88
  - cuda-nvvm-impl=13.0.88
  - cuda-nvvm-tools=13.0.88
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-sanitizer-api=13.0.85
  - cuda-toolkit=11.7.1
  - cuda-tools=13.0.2
  - cuda-version=13.0
  - cuda-visual-tools=13.0.2
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - khronos-opencl-icd-loader=2025.07.22
  - libcublas=13.1.0.3
  - libcublas-dev=13.1.0.3
  - libcufft=12.0.0.61
  - libcufft-dev=12.0.0.61
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcusolver=12.0.4.66
  - libcusolver-dev=12.0.4.66
  - libcusparse=12.6.3.3
  - libcusparse-dev=12.6.3.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libnpp=13.0.1.2
  - libnpp-dev=13.0.1.2
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=13.0.88
  - libnvjitlink-dev=13.0.88
  - libnvjpeg=13.0.1.86
  - libnvjpeg-dev=13.0.1.86
  - libnvptxcompiler-dev_win-64=13.0.88
  - libpng=1.6.50
  - libxml2=2.13.9
  - libzlib=1.3.1
  - nsight-compute=2025.3.1.4
  - opencl-headers=2025.07.22
  - openssl=3.0.18
  - pcre2=10.46
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - vs2017_win-64=19.16.27032.1
  - vswhere=3.1.7
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.61.1
      - idna==3.11
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - numpy==2.2.6
      - packaging==25.0
      - pillow==12.0.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - threadpoolctl==3.6.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - typing-extensions==4.15.0
      - urllib3==2.6.2
prefix: C:\Users\peter\miniconda3\envs\torch117
